<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="cube">

  <xacro:macro name="base_block" params="length cube_idx">
    <link name="cube${cube_idx}_link">
      <visual>
        <geometry>
          <box size="${length} ${length} ${length/2}"/>
          <material name="">
            <color rgba="0.9 0.9 0.9 1" />
          </material>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="${length} ${length} ${length/2}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="top_cube" params="length suffix cube_idx">
    <link name="childcube_${cube_idx}${suffix}">
      <visual>
        <geometry>
          <box size="${length/2} ${length/2} ${length/2}"/>
          <material name="">
            <color rgba="0.9 0.9 0.9 1" />
          </material>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="${length/2} ${length/2} ${length/2}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="colour_cube" params="length x_offset cube_idx">
    <xacro:base_block length="${length}" cube_idx="${cube_idx}" />
    <xacro:top_cube length="${length}" suffix="1" cube_idx="${cube_idx}"/>
    <xacro:top_cube length="${length}" suffix="2" cube_idx="${cube_idx}"/>
    <xacro:top_cube length="${length}" suffix="3" cube_idx="${cube_idx}"/>
    <xacro:top_cube length="${length}" suffix="4" cube_idx="${cube_idx}"/>

    <joint name="world2cube${cube_idx}_joint" type="fixed">
      <parent link="world" />
      <child link = "cube${cube_idx}_link" />
      <origin xyz="${x_offset} 0.7 ${0.7125+0.0127+length/4}" rpy="3.1415926 0.0 3.1415926" />
    </joint>

    <joint name="cube${cube_idx}_1_2_base" type="fixed">
      <parent link="cube${cube_idx}_link" />
      <child link = "childcube_${cube_idx}1" />
      <origin xyz="${-length/4} ${-length/4} ${-length/2}" rpy="0 0 0" />
    </joint>

    <joint name="cube${cube_idx}_2_2_base" type="fixed">
      <parent link="cube${cube_idx}_link" />
      <child link = "childcube_${cube_idx}2" />
      <origin xyz="${length/4} ${-length/4} ${-length/2}" rpy="0 0 0" />
    </joint>

    <joint name="cube${cube_idx}_3_2_base" type="fixed">
      <parent link="cube${cube_idx}_link" />
      <child link = "childcube_${cube_idx}3"/>
      <origin xyz="${-length/4} ${length/4} ${-length/2}" rpy="0 0 0" />
    </joint>

    <joint name="cube${cube_idx}_4_2_base" type="fixed">
      <parent link="cube${cube_idx}_link" />
      <child link = "childcube_${cube_idx}4" />
      <origin xyz="${length/4} ${length/4} ${-length/2}" rpy="0 0 0" />
    </joint>

    <gazebo reference="cube${cube_idx}_link">
      <material>Gazebo/Blue</material>
      <kinematic>1</kinematic>
      <selfCollide>1</selfCollide>
    </gazebo>

    <gazebo reference="childcube_${cube_idx}1">
      <material>Gazebo/Red</material>
      <kinematic>1</kinematic>
      <selfCollide>1</selfCollide>
    </gazebo>

    <gazebo reference="childcube_${cube_idx}2">
      <material>Gazebo/Purple</material>
      <kinematic>1</kinematic>
      <selfCollide>1</selfCollide>
    </gazebo>

    <gazebo reference="childcube_${cube_idx}3">
      <material>Gazebo/Yellow</material>
      <kinematic>1</kinematic>
      <selfCollide>1</selfCollide>
    </gazebo>

    <gazebo reference="childcube_${cube_idx}4">
      <material>Gazebo/Green</material>
      <kinematic>1</kinematic>
      <selfCollide>1</selfCollide>
    </gazebo>

  </xacro:macro>

  <link name="world" />
  <xacro:colour_cube length="0.08" x_offset="0" cube_idx="1" />
  <xacro:colour_cube length="0.08" x_offset="0.4" cube_idx="2" />
  <xacro:colour_cube length="0.08" x_offset="-0.4" cube_idx="3" />

</robot>
