<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="cube">

  <xacro:macro name="base_block" params="length">
    <link name="cube_link">
      <visual>
        <geometry>
          <box size="${length} ${length} ${length/2}"/>
          <material name="">
            <color rgba="0.9 0.9 0.9 1" />
          </material>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="${length} ${length} ${length/2}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="top_cube" params="length suffix">
    <link name="cube_${suffix}">
      <visual>
        <geometry>
          <box size="${length/2} ${length/2} ${length/2}"/>
          <material name="">
            <color rgba="0.9 0.9 0.9 1" />
          </material>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <box size="${length/2} ${length/2} ${length/2}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia
          ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0"/>
      </inertial>
    </link>
  </xacro:macro>

  <xacro:macro name="colour_cube" params="length">
    <xacro:base_block length="${length}" />
    <xacro:top_cube length="${length}" suffix="1"/>
    <xacro:top_cube length="${length}" suffix="2"/>
    <xacro:top_cube length="${length}" suffix="3"/>
    <xacro:top_cube length="${length}" suffix="4"/>
    <link name="world" />

    <joint name="world2cube_joint" type="fixed">
      <parent link="world" />
      <child link = "cube_link" />
      <origin xyz="0.0 0.7 ${0.7125+0.0127+length/4}" rpy="3.1415926 0.0 3.1415926" />
    </joint>

    <joint name="cube_1_2_base" type="fixed">
      <parent link="cube_link" />
      <child link = "cube_1" />
      <origin xyz="${-length/4} ${-length/4} ${-length/2}" rpy="0 0 0" />
    </joint>

    <joint name="cube_2_2_base" type="fixed">
      <parent link="cube_link" />
      <child link = "cube_2" />
      <origin xyz="${length/4} ${-length/4} ${-length/2}" rpy="0 0 0" />
    </joint>

    <joint name="cube_3_2_base" type="fixed">
      <parent link="cube_link" />
      <child link = "cube_3" />
      <origin xyz="${-length/4} ${length/4} ${-length/2}" rpy="0 0 0" />
    </joint>

    <joint name="cube_4_2_base" type="fixed">
      <parent link="cube_link" />
      <child link = "cube_4" />
      <origin xyz="${length/4} ${length/4} ${-length/2}" rpy="0 0 0" />
    </joint>

  </xacro:macro>

  <xacro:colour_cube length="0.08" />

  <gazebo reference="cube_link">
    <material>Gazebo/Blue</material>
    <kinematic>1</kinematic>
    <selfCollide>1</selfCollide>
  </gazebo>

  <gazebo reference="cube_1">
    <material>Gazebo/Red</material>
    <kinematic>1</kinematic>
    <selfCollide>1</selfCollide>
  </gazebo>

  <gazebo reference="cube_2">
    <material>Gazebo/Purple</material>
    <kinematic>1</kinematic>
    <selfCollide>1</selfCollide>
  </gazebo>

  <gazebo reference="cube_3">
    <material>Gazebo/Yellow</material>
    <kinematic>1</kinematic>
    <selfCollide>1</selfCollide>
  </gazebo>

  <gazebo reference="cube_4">
    <material>Gazebo/Green</material>
    <kinematic>1</kinematic>
    <selfCollide>1</selfCollide>
  </gazebo>

</robot>
